### PR TITLE
Add lintr style check

### LINKED ISSUE #11: Add style checking

### LINKED ISSUE #13: Add pull request template
Suggested in #12

### PR DESCRIPTION
**Pull request by rccreswell**
Closes #11 
Closes #13

### CODE REVIEW

**Comment by rccreswell** [comment]
This workflow adds the same lintr checks we are using in comoDTC.
In this default configuration, style problems don't necessarily cause the check to fail. Most of the transgressions just get a warning comment in the PR code.

@ben18785 if you'd like to make it stricter so it fails the check when style problems are present, I think I can easily do that with the expect_lint_free function.

**Comment by ben18785** [comment]
Thanks @rcw5890 -- that's great. Given that style fails don't cause fails, how about adding a Github PR template that adds a checkbox asking if a person has done style checks via Lintr?

**Comment by rccreswell** [comment]
> Thanks @rcw5890 -- that's great. Given that style fails don't cause fails, how about adding a Github PR template that adds a checkbox asking if a person has done style checks via Lintr?

I put down a first attempt for the template---it mentions the style check and several other things that came to mind.

**Review by ben18785 — APPROVED** [review]
Looks great -- thanks @rcw5890

**Pull request merged**
