### PR TITLE
Births, natural deaths and waning natural immunity

### PR DESCRIPTION
**Pull request by ben18785**
Adds a model and vignette that allows: births, natural deaths and waning natural immunity (i.e. protection from reinfection due to a previous infection). The vignette shows how epidemic waves occur and gives an order of magnitude estimate for the case counts that would be reached at endemic equilibrium for COVID-19.

Addresses #14.

### CODE REVIEW

**Comment by solveigvandervegt** [comment]
Looks really good! I fixed some typos and grammar issues, hope that's ok. The only thing that I have some reservations about is the computation of beta. I know it comes from the other vignette but since you already mention that in the text, I would be tempted to just set the values here and not derive it again. It's quite a confusing computation out of context and if people want to know why these values are used, they know where to look.

**Comment by solveigvandervegt** [comment]
Oh also, the last situation in the references list is missing an author?

**Comment by solveigvandervegt** [comment]
And is it correct that there are no tests for this class? I cannot see them in the test that folder

**Comment by ben18785** [comment]
Thanks @solveigvandervegt -- you're spot on re: tests. I'll add some now. I'll also address your other comments.

**Comment by ben18785** [comment]
Thanks @solveigvandervegt I've added tests. Re: R_0, I actually quite favour having it in there (as a more pedagogical aspect of the vignette). I've added a little more text that explains both the relevance of the calculation (for the vignette itself) and the calculation. Anyhow, see what you think!

**Comment by solveigvandervegt** [comment]
Hey Ben, yeah sorry you are totally right re: R0 and beta, I read it wrong. I think my point is actually about how gamma and mu are computed. The zeta and ifr come a bit out of nowhere, though I know this is addressed in the other vignette. Sorry for the poorly written comment before!

**Comment by ben18785** [comment]
Cool no worries -- I've now added an explicit reference to the other vignette. I actually think that this will partly be addressed by #67 so perhaps we can leave this as is for now and address later?

**Comment by solveigvandervegt** [comment]
Yeah sure, sounds good!

**Pull request merged**
